### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/super-mario-bros-like-game#4]
v0.1
- [ ] Stray away from getTree().ChangeScene() and work towards prefabs as it may help in the long run
- [ ] Work on a enemy that walks back and fourth
- [ ] Work on adding more stuff to player like for e.g. wall jumping and better jump physics in general
